name: open
version: 1.3.0

description: Open whatever you want, such as URLs, files or executables, regardless of the platform you use.
homepage: https://dev.belin.io/open.dart
issue_tracker: https://github.com/cedx/open.dart/issues
repository: https://github.com/cedx/open.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  open_cli: open_cli

dependencies:
  build_cli_annotations: ^1.2.0

dev_dependencies:
  build_cli: ^1.3.7
  build_runner: ^1.8.0
  build_test: ^1.0.0
  build_version: ^2.0.1
  coverage: ^0.13.9
  coveralls: ^5.7.0
  grinder: ^0.8.4
  test: ^1.14.2
