name: open
version: 1.2.0

description: Open whatever you want, such as URLs, files or executables, regardless of the platform you use.
homepage: https://dev.belin.io/open.dart
issue_tracker: https://github.com/cedx/open.dart/issues
repository: https://github.com/cedx/open.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  open_cli: open_cli

dependencies:
  build_cli_annotations: ^1.1.0

dev_dependencies:
  build_cli: ^1.3.6
  build_runner: ^1.7.3
  build_test: ^0.10.11
  build_version: ^2.0.1
  grinder: ^0.8.3
  test: ^1.11.0
