name: open
version: 2.0.0

description: Open whatever you want, such as URLs, files or executables, regardless of the platform you use.
homepage: https://docs.belin.io/open.dart
issue_tracker: https://git.belin.io/cedx/open.dart/issues
repository: https://git.belin.io/cedx/open.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

executables:
  open_cli: open_cli

dependencies:
  build_cli_annotations: ^1.2.0

dev_dependencies:
  build_cli: ^1.3.9
  build_runner: ^1.10.0
  build_test: ^1.2.0
  build_version: ^2.0.1
  coverage: ^0.14.0
  coveralls: ^5.9.0
  test: ^1.14.7
