name: open
version: 2.0.0

description: Open whatever you want, such as URLs, files or executables, regardless of the platform you use.
homepage: https://cedx.github.io/open.dart
issue_tracker: https://github.com/cedx/open.dart/issues
repository: https://github.com/cedx/open.dart

environment:
  sdk: ">=2.10.0 <3.0.0"

executables:
  open_cli: open_cli

dependencies:
  build_cli_annotations: ^1.2.0

dev_dependencies:
  build_cli: ^1.3.10
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_version: ^2.0.1
  coverage: ^0.14.2
  coveralls: ^5.10.0
  test: ^1.15.7
